//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XXX_sell.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XXX_sell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _01 {
            get {
                object obj = ResourceManager.GetObject("01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1a0574f0a66e920c_03a9e98a58ddcf91_edb51dfcb91615e6b85761a7efc4c445 {
            get {
                object obj = ResourceManager.GetObject("1a0574f0a66e920c-03a9e98a58ddcf91-edb51dfcb91615e6b85761a7efc4c445", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1a3d496ea49bb150_0ab91eb34a731317_2c9f3c67746766b96269bc7e0822945e {
            get {
                object obj = ResourceManager.GetObject("1a3d496ea49bb150-0ab91eb34a731317-2c9f3c67746766b96269bc7e0822945e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1dcce46d92821c123ba430e2bb645445 {
            get {
                object obj = ResourceManager.GetObject("1dcce46d92821c123ba430e2bb645445", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3939013B5DEF4824B6AF2DB9447C4C7E {
            get {
                object obj = ResourceManager.GetObject("3939013B5DEF4824B6AF2DB9447C4C7E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3c28af542f2d49f7_44af7693092324ab_edabc8b284469208ff4f4917cded2c36 {
            get {
                object obj = ResourceManager.GetObject("3c28af542f2d49f7-44af7693092324ab-edabc8b284469208ff4f4917cded2c36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3c28af542f2d49f7_da1566425074a021_3653465a8d375b63a57aaaa44bf3db51 {
            get {
                object obj = ResourceManager.GetObject("3c28af542f2d49f7-da1566425074a021-3653465a8d375b63a57aaaa44bf3db51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4eb507341e0c99da_b1ba2743a36c0b45_1b26c585ee0d9da09d89226ed8cad943 {
            get {
                object obj = ResourceManager.GetObject("4eb507341e0c99da-b1ba2743a36c0b45-1b26c585ee0d9da09d89226ed8cad943", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5cfc73a05407de00_e95930cc9cacb570_027c56a94133397dd73a36b3ed4872c7 {
            get {
                object obj = ResourceManager.GetObject("5cfc73a05407de00-e95930cc9cacb570-027c56a94133397dd73a36b3ed4872c7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ac75323d6b6de243_6f95e32275e1e6d6_4cd975ceabd39b6a0a4944f4b4c62039 {
            get {
                object obj = ResourceManager.GetObject("ac75323d6b6de243-6f95e32275e1e6d6-4cd975ceabd39b6a0a4944f4b4c62039", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ac75323d6b6de243_6f95e32275e1e6d6_4cd975ceabd39b6a0a4944f4b4c620391 {
            get {
                object obj = ResourceManager.GetObject("ac75323d6b6de243-6f95e32275e1e6d6-4cd975ceabd39b6a0a4944f4b4c620391", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap c989bf8cff2a0130cbe81af609e13efa {
            get {
                object obj = ResourceManager.GetObject("c989bf8cff2a0130cbe81af609e13efa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ca86e620b9e623ff_d1c9f350507d226e_7392394e704c0123cee206426b31ba20 {
            get {
                object obj = ResourceManager.GetObject("ca86e620b9e623ff-d1c9f350507d226e-7392394e704c0123cee206426b31ba20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap d7036c9a17f5fda2_ec8e047b4bd56cbf_eed6b6c8efbf4d0cbc3f6acd2e1bfcfb {
            get {
                object obj = ResourceManager.GetObject("d7036c9a17f5fda2-ec8e047b4bd56cbf-eed6b6c8efbf4d0cbc3f6acd2e1bfcfb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ea834ebbc9c8dae4_ea7fa0d8af0943e5_f11bd704746bca6c1c5931c5240bf1b8 {
            get {
                object obj = ResourceManager.GetObject("ea834ebbc9c8dae4-ea7fa0d8af0943e5-f11bd704746bca6c1c5931c5240bf1b8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap f13ca4be157d8983_b9e0c1d9d6b828ce_d75941af34230a408081f78da9ab7423 {
            get {
                object obj = ResourceManager.GetObject("f13ca4be157d8983-b9e0c1d9d6b828ce-d75941af34230a408081f78da9ab7423", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap f13ca4be157d8983_b9e0c1d9d6b828ce_f6091d936165d0642637cc4480ef9617 {
            get {
                object obj = ResourceManager.GetObject("f13ca4be157d8983-b9e0c1d9d6b828ce-f6091d936165d0642637cc4480ef9617", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap psb2NZYCZ05 {
            get {
                object obj = ResourceManager.GetObject("psb2NZYCZ05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap th2TBV42OS {
            get {
                object obj = ResourceManager.GetObject("th2TBV42OS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap thKBWQ27WM {
            get {
                object obj = ResourceManager.GetObject("thKBWQ27WM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
